"""Configs for the word-shuffled Pythia connectomes (LOG.md Iteration 32).

    python scripts/make_shuffle_configs.py

One config per Pythia config in configs/pythia/: identical (model, checkpoint, domains,
documents, seeds, token counts), except that words are permuted within each 1,024-token
window (`data_kwargs: {shuffle_words: true}`), no null tree is computed, and the output
goes to its own tree, results/pythia_shuffled/pythia-<size>/step<k>. Only the connectivity
is run; `parcelmate.bin.connectome_consistency` reads it and purges it.
"""

import glob
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'configs', 'pythia')
OUT = os.path.join(HERE, '..', 'configs', 'pythia_shuffled')

HEADER = """# Word-shuffled twin of configs/pythia/%s (LOG.md Iteration 32). Generated by
# scripts/make_shuffle_configs.py; edit that script, not this file.
#
# Same documents, seeds and tokens as the original; words permuted within each 1,024-token
# window; no null; connectivity only (then connectome_consistency, which purges it).
"""


def main():
    os.makedirs(OUT, exist_ok=True)
    for path in sorted(glob.glob(os.path.join(SRC, 'pythia-*_step*.yml'))):
        name = os.path.basename(path)
        cfg = yaml.safe_load(open(path))
        cfg['output_dir'] = cfg['output_dir'].replace('results/pythia/', 'results/pythia_shuffled/', 1)
        c = cfg['connectivity']
        c['null_model'] = None
        c['data_kwargs'] = dict(shuffle_words=True)
        cfg.pop('parcellation', None)
        cfg.pop('parcellation_variants', None)
        with open(os.path.join(OUT, name), 'w') as f:
            f.write(HEADER % name + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False))
        print(os.path.join('configs', 'pythia_shuffled', name))


if __name__ == '__main__':
    main()
