"""Write one config per (Pythia size, checkpoint) for the training-dynamics experiment.

    python scripts/make_pythia_configs.py

LOG.md Iteration 22. Every config applies the confirmed pipeline (Iteration 21) unchanged,
except that all MLP neurons are units (`units_per_layer: null`) and the connectivity step
writes the split halves directly (`outputs: [halves]`), which the parcellation and score
steps then consume without an `avg` file. The generated files are committed, so each run is
reproducible from the repository alone; this script is the record of how they were made.
"""

import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'configs', 'pythia')

# Sizes with all MLP neurons as units. 410m (24 x 4096 = 98,304 units, a 39 GB matrix)
# needs out-of-core code and is deferred.
SIZES = {
    '70m': dict(layers=6, neurons=2048),
    '160m': dict(layers=12, neurons=3072),
}

# Step 0 (the initialisation) plus ten checkpoints spaced by a factor of about 4 over the
# 143,000 steps of training. Pythia saves every power of two up to 512 and every 1,000
# steps after that, so every one of these exists.
STEPS = [0, 1, 4, 16, 64, 256, 1000, 4000, 16000, 64000, 143000]

DOMAINS = ['wikitext', 'bookcorpus', 'agnews', 'tldr17']

HEADER = """# Pythia training dynamics (LOG.md Iteration 22): %(model)s at training step %(step)d.
# Generated by scripts/make_pythia_configs.py; edit that script, not this file.
#
# The confirmed pipeline (Iteration 21) on ALL %(layers)d x %(neurons)d = %(units)d MLP
# neurons: |r| connectome, Fisher-transformed standardized profiles sparsified to their top
# 10%%, PCA-100 unwhitened, Lloyd k-means with 200 restarts and Hungarian consensus, k = 100,
# fitted within one domain. Same seed as every earlier run, so every checkpoint sees the
# same documents; only the weights differ along the training axis.
#
# The connectivity step writes the two split halves directly (`outputs: [halves]`) and the
# parcellation consumes only them; `-s purge_connectivity` deletes the %(gb).1f GB of
# connectivity per tree once metrics/scores.csv exists.
"""


RESID_HEADER = """#
# RESIDUAL CONNECTOME (LOG.md Iteration 39): before correlating, every unit's activation has
# what token type and position predict removed (a joint least-squares fit, on a reference
# portion of every domain pooled over the four domains, disjoint from the analysed text;
# parcelmate/residual.py). The analysed documents, samples, halves and every later step are
# exactly those of configs/pythia/.
"""


def config(size, step, resid=False):
    spec = SIZES[size]
    model = 'EleutherAI/pythia-%s' % size
    units = spec['layers'] * spec['neurons']
    out_dir = 'results/%s/pythia-%s/step%d' % ('pythia_resid' if resid else 'pythia', size, step)
    cfg = dict(
        output_dir=out_dir,
        seed=42,
        purge_connectivity=True,
        connectivity=dict(
            model_name=model,
            revision='step%d' % step,
            unit_type='mlp',
            units_per_layer=None,
            n_samples=4,
            domains=list(DOMAINS),
            seq_len=1024,
            n_tokens=None,
            split='train',
            take=100000,
            wrap=True,
            shuffle=True,
            batch_size=8,
            highpass=None,
            lowpass=None,
            step=0.2,
            timecourse_pca_components=None,
            timecourse_ica_components=None,
            eps=1.0e-3,
            null_model='circshift',
            n_surrogates=0,
            outputs=['halves'],
        ),
        parcellation=dict(
            n_networks=100,
            n_samples=200,
            clustering='kmeans',
            binarize_connectivity=False,
            fisher_transform=True,
            standardize_profiles=True,
            sparsify_profiles=True,
            connectivity_pca_components=100,
            pca_whiten=False,
            store_samples=True,
            parcellate_keys=['halfA', 'halfB'],
            clustering_kwargs=None,
            n_alignments=None,
            weight_samples=False,
            parcellate_samples=False,
        ),
        parcellation_variants={'final': {}},
    )
    if resid:
        cfg['connectivity'].update(residualize='token_position', residual_ref_tokens=None,
                                   residual_min_count=3)
    header = HEADER % dict(model=model, step=step, layers=spec['layers'],
                           neurons=spec['neurons'], units=units,
                           gb=4 * 2 * units * units * 4 / 1e9)
    if resid:
        header += RESID_HEADER
    return header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)


def config_name(size, step, resid=False):
    return '%s-%s_step%d.yml' % ('pythia_resid' if resid else 'pythia', size, step)


if __name__ == '__main__':
    # `--resid` writes the residual-connectome twins into configs/pythia_resid/.
    resid = '--resid' in sys.argv
    out = OUT + ('_resid' if resid else '')
    os.makedirs(out, exist_ok=True)
    for size in SIZES:
        for step in STEPS:
            path = os.path.join(out, config_name(size, step, resid))
            with open(path, 'w') as f:
                f.write(config(size, step, resid))
            print(os.path.relpath(path, os.path.join(HERE, '..')))
