"""Write the Qwen3.5 configs for the out-of-core pipeline (LOG.md Iteration 25).

    python scripts/make_qwen_configs.py

The confirmed pipeline (Iteration 21) on ALL MLP neurons, connectivity stored as float16
tiles (`storage: tiled_fp16`), halves only, purged after scoring. The 2B config runs two
domains as the full-scale check of the out-of-core path (350 GB written); the 4B config
runs the four prose domains (2.8 TB written, 1.75 TB peak on disk).
"""

import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'configs', 'qwen35')

MODELS = {
    'qwen3.5-2b': dict(model='Qwen/Qwen3.5-2B', layers=24, neurons=6144,
                       domains=['wikitext', 'bookcorpus']),
    # Four prose domains were planned (Iteration 26); bookcorpus, agnews and tldr17 were
    # cancelled on 2026-09-23 before their connectivity ran, when the pooled design below
    # replaced them (Iteration 31). Only wikitext was computed, so the config says so.
    'qwen3.5-4b': dict(model='Qwen/Qwen3.5-4B', layers=32, neurons=9216,
                       domains=['wikitext']),
    # Pooled connectivity (Iteration 31): ONE pair of halves, the pseudo-domain `pooled`,
    # Fisher-averaged over 2 samples x 40,960 tokens of each of five domains (one sample per
    # domain per half), for the comparison with the attribution-patching circuits. Separate
    # output trees, so it never mixes with the single-domain connectivity above.
    'qwen3.5-2b-pool5': dict(model='Qwen/Qwen3.5-2B', layers=24, neurons=6144, pool_as='pooled',
                             domains=['wikitext', 'bookcorpus', 'agnews', 'tldr17', 'codeparrot']),
    'qwen3.5-4b-pool5': dict(model='Qwen/Qwen3.5-4B', layers=32, neurons=9216, pool_as='pooled',
                             domains=['wikitext', 'bookcorpus', 'agnews', 'tldr17', 'codeparrot']),
}
POOL_SAMPLES = 2
POOL_TOKENS = 40960   # per sample: 40 sequences of 1,024; 5 batches of 8

POOL_HEADER = """# %(model)s, all %(layers)d x %(neurons)d = %(units)d MLP neurons, POOLED over %(nd)d
# domains (LOG.md Iteration 31). Generated by scripts/make_qwen_configs.py; edit that
# script, not this file.
#
# One pseudo-domain `%(pool)s`: half A = sample 1 of every domain, half B = sample 2, each
# sample %(tok)d tokens and z-scored on its own, each half the Fisher mean over its %(nd)d
# samples. For comparison with the patching circuits only (independent localiser, so
# pooling is no double dipping); the domain-generality results stay single-domain. %(gb).0f GB
# per half, %(total).0f GB written for 2 trees x 2 halves, purged after scoring. Everything
# else is the confirmed pipeline (Iteration 21).
"""

HEADER = """# %(model)s, all %(layers)d x %(neurons)d = %(units)d MLP neurons, out of core (LOG.md
# Iteration 25). Generated by scripts/make_qwen_configs.py; edit that script, not this file.
#
# Connectivity is written as float16 row tiles (%(gb).0f GB per half, %(total).0f GB for
# the run's %(nd)d domains x 2 trees x 2 halves); the null tree's tiles are purged after its
# parcellation (`-s purge_null_connectivity`, per domain) and the real tree's after scoring.
# Everything else is the confirmed pipeline: Fisher-transformed standardized profiles
# sparsified to their top 10%%, PCA-100 unwhitened (randomized), Lloyd with 200 restarts,
# Hungarian consensus, k = 100, fitted within one domain.
"""


def config(name, spec):
    units = spec['layers'] * spec['neurons']
    gb = units * units * 2 / 1e9
    cfg = dict(
        output_dir='results/qwen35/%s' % name,
        seed=42,
        purge_connectivity=True,
        connectivity=dict(
            model_name=spec['model'],
            revision=None,
            unit_type='mlp',
            units_per_layer=None,
            n_samples=POOL_SAMPLES if spec.get('pool_as') else 4,
            domains=list(spec['domains']),
            seq_len=1024,
            n_tokens=POOL_TOKENS if spec.get('pool_as') else None,
            split='train',
            take=100000,
            wrap=True,
            shuffle=True,
            batch_size=8,
            highpass=None,
            lowpass=None,
            step=0.2,
            timecourse_pca_components=None,
            timecourse_ica_components=None,
            eps=1.0e-3,
            null_model='circshift',
            n_surrogates=0,
            outputs=['halves'],
            storage='tiled_fp16',
        ),
        parcellation=dict(
            n_networks=100,
            n_samples=200,
            clustering='kmeans',
            binarize_connectivity=False,
            fisher_transform=True,
            standardize_profiles=True,
            sparsify_profiles=True,
            connectivity_pca_components=100,
            pca_whiten=False,
            store_samples=True,
            parcellate_keys=['halfA', 'halfB'],
            clustering_kwargs=None,
            n_alignments=None,
            weight_samples=False,
            parcellate_samples=False,
        ),
        parcellation_variants={'final': {}},
    )
    if spec.get('pool_as'):
        cfg['connectivity']['pool_as'] = spec['pool_as']
        cfg['score'] = dict(domains=[spec['pool_as']])
        return POOL_HEADER % dict(model=spec['model'], layers=spec['layers'], neurons=spec['neurons'],
                                  units=units, nd=len(spec['domains']), pool=spec['pool_as'],
                                  tok=POOL_TOKENS, gb=gb, total=gb * 4) + \
            yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)
    header = HEADER % dict(model=spec['model'], layers=spec['layers'], neurons=spec['neurons'],
                           units=units, gb=gb, total=gb * 4 * len(spec['domains']),
                           nd=len(spec['domains']))
    return header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    for name, spec in MODELS.items():
        path = os.path.join(OUT, name + '.yml')
        with open(path, 'w') as f:
            f.write(config(name, spec))
        print(os.path.relpath(path, os.path.join(HERE, '..')))
